# Generated by Django 5.0.7 on 2025-01-16 09:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_card_no', models.CharField(default=str, max_length=15)),
                ('beneficiary_name', models.CharField(max_length=20)),
                ('beneficiary_email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('beneficiary_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\d{10,13}$', message='Enter a valid phone number.')])),
                ('beneficiary_address', models.CharField(default=str, max_length=100)),
                ('beneficiary_aadhaar', models.CharField(default=str, max_length=10)),
                ('beneficiary_state', models.CharField(default=str, max_length=20)),
                ('beneficiary_pincode', models.CharField(default=str, max_length=6)),
                ('beneficiary_family_size', models.IntegerField(default=int)),
                ('beneficiary_family', models.JSONField(default=list)),
                ('beneficiary_otp', models.CharField(default=None, max_length=6)),
                ('beneficiary_password', models.CharField(default=str, max_length=128)),
                ('beneficiary_card', models.CharField(choices=[('select', 'Select'), ('yellow', 'Yellow'), ('white', 'White'), ('saffron', 'Saffron'), ('green', 'Green')], default='select', max_length=20)),
                ('beneficiary_type', models.CharField(choices=[('select', 'Select'), ('superuser', 'Superuser'), ('fps', 'Fair Price Shop'), ('user', 'User')], default='select', max_length=20, null=True)),
                ('bene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
