# Generated by Django 5.0.7 on 2025-01-16 18:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ration_Card',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('beneficiary_card_no', models.CharField(default=str, max_length=15)),
                ('ration_card_beneficiary_name', models.CharField(default=str, max_length=20)),
                ('b_ration_address', models.CharField(default=str, max_length=100)),
                ('b_ration_aadhaar', models.CharField(default=str, max_length=10)),
                ('b_ration_state', models.CharField(default=str, max_length=20)),
                ('b_ration_pincode', models.CharField(default=str, max_length=6)),
                ('b_ration_family_size', models.IntegerField(default=1)),
                ('b_ration_family', models.JSONField(default=list)),
                ('ration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
