# Generated by Django 5.0.7 on 2025-01-16 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_ration_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ration_card',
            name='ration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.beneficiaries'),
        ),
    ]
