# Generated by Django 5.0.7 on 2025-01-16 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_ration_card_ration'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaries',
            name='ration_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.ration_card'),
        ),
    ]
