# Generated by Django 5.0.7 on 2025-01-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_beneficiaries_ration_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration_card',
            name='rfid_tag',
            field=models.CharField(default='default_rfid_tag', max_length=15),
        ),
    ]
