# Generated by Django 5.0.7 on 2025-03-10 09:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_ration_card_rfid_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fps_code', models.CharField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FPSInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheat_initial', models.IntegerField(default=1000)),
                ('rice_initial', models.IntegerField(default=1000)),
                ('sugar_initial', models.IntegerField(default=1000)),
                ('wheat_current', models.IntegerField(default=1000)),
                ('rice_current', models.IntegerField(default=1000)),
                ('sugar_current', models.IntegerField(default=1000)),
                ('last_reset', models.DateField(default=django.utils.timezone.now)),
                ('fps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.fps')),
            ],
        ),
        migrations.CreateModel(
            name='FPSProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='fps_profiles/')),
                ('fps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.fps')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
